// Generated by CoffeeScript 1.4.0
(function() {
  var should;

  should = chai.should();

  describe("Tests in Coffeescript", function() {
    return it("true should be truthy", function() {
      this.employees = require('../../public/scripts/collections/collection.Employees.js');
      return true.should.be.ok;
    });
  });

}).call(this);
