// Generated by CoffeeScript 1.3.3
(function() {
  var DataStore;

  DataStore = (function() {

    function DataStore() {
      this.mongoose = require('mongoose');
      this.con = this.mongoose.connect('mongodb://localhost:8120/ekmHoliCal');
      this.schemas = require('./schemas');
    }

    return DataStore;

  })();

  module.exports = DataStore;

}).call(this);
